// Regenerate src/fonts-inline.ts from assets/fonts/*.woff2.
// The brand display face (Clash Display) is inlined as base64 data URIs so
// Remotion font-loading can't hang: no network fetch => FontFace.load() resolves
// instantly, with no dependency on wall-clock timers (which Remotion mocks).
//   node scripts/gen-fonts.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const FONTS = path.join(ROOT, 'assets', 'fonts')
const MAP = [
  ['500', 'ClashDisplay-Medium.woff2'],
  ['600', 'ClashDisplay-Semibold.woff2'],
  ['700', 'ClashDisplay-Bold.woff2'],
]

const entries = MAP.map(([weight, file]) => {
  const b64 = fs.readFileSync(path.join(FONTS, file)).toString('base64')
  return `  { weight: "${weight}", dataUrl: "data:font/woff2;base64,${b64}" },`
})

const out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Base64 of assets/fonts/*.woff2. Inlining the brand display face as data URIs
// makes Remotion font-loading bulletproof: no network fetch => FontFace.load()
// resolves instantly, no timer/hang risk (Remotion mocks wall-clock timers).
export const FONT_FACES: { weight: string; dataUrl: string }[] = [
${entries.join('\n')}
]
`
fs.writeFileSync(path.join(ROOT, 'src', 'fonts-inline.ts'), out)
console.log(`wrote src/fonts-inline.ts (${(out.length / 1024).toFixed(0)}KB)`)
