/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as CirclesNewRouteImport } from './routes/circles.new'
import { Route as CircleIdRouteImport } from './routes/circle.$id'
import { Route as CIdRouteImport } from './routes/c.$id'

const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesNewRoute = CirclesNewRouteImport.update({
  id: '/circles/new',
  path: '/circles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIdRoute = CircleIdRouteImport.update({
  id: '/circle/$id',
  path: '/circle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/c/$id': typeof CIdRoute
  '/circle/$id': typeof CircleIdRoute
  '/circles/new': typeof CirclesNewRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/c/$id': typeof CIdRoute
  '/circle/$id': typeof CircleIdRoute
  '/circles/new': typeof CirclesNewRoute
  '/circles': typeof CirclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/c/$id': typeof CIdRoute
  '/circle/$id': typeof CircleIdRoute
  '/circles/new': typeof CirclesNewRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/demo'
    | '/invite'
    | '/c/$id'
    | '/circle/$id'
    | '/circles/new'
    | '/circles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/demo'
    | '/invite'
    | '/c/$id'
    | '/circle/$id'
    | '/circles/new'
    | '/circles'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/demo'
    | '/invite'
    | '/c/$id'
    | '/circle/$id'
    | '/circles/new'
    | '/circles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DemoRoute: typeof DemoRoute
  InviteRoute: typeof InviteRoute
  CIdRoute: typeof CIdRoute
  CircleIdRoute: typeof CircleIdRoute
  CirclesNewRoute: typeof CirclesNewRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/new': {
      id: '/circles/new'
      path: '/circles/new'
      fullPath: '/circles/new'
      preLoaderRoute: typeof CirclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/$id': {
      id: '/circle/$id'
      path: '/circle/$id'
      fullPath: '/circle/$id'
      preLoaderRoute: typeof CircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DemoRoute: DemoRoute,
  InviteRoute: InviteRoute,
  CIdRoute: CIdRoute,
  CircleIdRoute: CircleIdRoute,
  CirclesNewRoute: CirclesNewRoute,
  CirclesIndexRoute: CirclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
